img_prompt: >
  {DEFAULT_IMAGE_TOKEN}
  As an expert aerial‐image analyst, describe every visible detail: terrain and land use, vegetation patterns, water bodies, roads and buildings, textures, colors, shadows, spatial relationships, and any human activity. Be precise yet concise.